[package]
name = "simple_astar"
version = "0.2.0"
authors = ["tylervipond"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
smallvec = "1.5.0"
fxhash = "0.2.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "astar_benchmark"
harness = false
